# Linode instance
version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-instance
    restart: unless-stopped
    networks:
      - payload-network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: strongpassword
    volumes:
      - mongo_data:/data/db

  payload:
    build: .
    container_name: payload-instance
    restart: unless-stopped
    networks:
      - payload-network
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://admin:strongpassword@mongo:27017/payload-db?authSource=admin
      PAYLOAD_SECRET: supersecret
      PORT: 3000
    volumes:
      - .:/payload-app-starter
      - /payload-app-starter/node_modules

networks:
  payload-network:

volumes:
  mongo_data: